CREATE TABLE [dbo].[Label]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	[Picture] NVARCHAR(MAX) NOT NULL,
	[Location] NVARCHAR(50) NOT NULL,
	[FoundationYear] SMALLINT NOT NULL,

	CONSTRAINT [PK_Label] PRIMARY KEY ([Id]),
	CONSTRAINT [UK_Label_Name] UNIQUE ([Name])
);